#!/bin/bash
# This script automatically runs all python tests on the folder given in param1 
# And then creates summary excel file and pie chart.
# usage: /auto_run <dir of images to test> <number of images to test>
# example usage for bulk: 
#	for x in $(ls image_folders) ; do  # ( <- image_folder is a dir with subdirs of >500 images in each)
# 	./auto_run $x 500
# 	done

#-- Getting user info
imgfolderpath="$1"
numimgs="$2"

[[ ! -n "$numimgs" ]] && echo 'usage: ./auto_run <path to images> <number of images' && exit 1

#--Setting Variables
base=$(basename $imgfolderpath)  # getting bas dir name (ex: a from c/b/a) 
testfolder=$(pwd)/auto_test_"$base"_$(date +'%y-%m-%d__%s')
tests_arr=(brighten crop resize rotate nothing)

echo Test Folder: $base

echo Getting images from: $imgfolderpath and testing: $numimgs for each test 

#-- Making directories
mkdir $testfolder
for x in ${tests_arr[@]};do
	mkdir $testfolder/$x
done

# -- Copy folder with images into test folder
for x in ${tests_arr[@]};do
	cp -r $imgfolderpath $testfolder/$x
done 

#-- Select numimgs images in each test at random to run test on 
for t in ${tests_arr[@]};do
	for x in $(shuf -e $(find $testfolder/$t -not -type d  -and -not -name "*.txt") -n $numimgs);do 
		python $t'.py' $x 
	done	
done 

#--  Run test
./test_cmd $testfolder

#-- summarizing 
# reltestfolder=$(basename $testfolder)
python summarize.py --root $testfolder --type exact 
python summarize.py --root $testfolder --type similar 
python draw_chart.py ${testfolder}/exact_summary.xlsx
python draw_chart.py ${testfolder}/similar_summary.xlsx

#-- cleaning up raw data
mkdir ${testfolder}/'raw_output_data'
mv ${testfolder}/*.txt ${testfolder}/'raw_output_data'



