#!/bin/bash
orig_dir=$(pwd)
cd ../ImgOrganizer/x64/Release
x=$orig_dir/"tests"
truncate -s 0 $x/*output.txt
for i in $(ls $x)
	 do 	
		./ImgOrganizer.exe $x/$i	
	 done
for i in $(ls $x | grep output)
	do
		echo $x/$i
		grep  -c "/*/" $x/$i  	
	done
cd $orig_dir
